Develop: criado endpoint subtraction
bartomsilva/four-operations pull request #5
Opened 2023-06-19 22:19 UTC by ffernanda85

Pessoal, perdoem a demora. Espero que eu tenha entendido corretamente o projeto e feito certinho! Fiquei com a parte de subtração.

2023-06-19 23:57 UTC, bartomsilva requested changes
Olá Flavia, primeiramente prabéns! ficou excelente, penas uma observação pode modificar para retornar apenas o resultado?

2023-06-20 20:39 UTC, ffernanda85 commented
Amigo? Dá uma olhada se mostra a modificação... 
Não sei se fiz certo,  está dando conflito e não me permite fazer um novo PR.
Vê se dá pra tu visualizar se está certa a alteração

2023-06-20 21:18 UTC, bartomsilva approved these changes
Oi Flávia, não deveria remover os imports, lembrando que não faz parte do rotina a ser criada.

2023-06-20 21:22 UTC, closed without merging

2023-06-20 21:22 UTC, bartomsilva commented
ficou misturado os dados